version: "3.8"

services:
  backend:
    image: bhoominaik16/todo-backend:latest
    container_name: todo_backend
    ports:
      - "5001:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/todo
    depends_on:
      - mongo

  frontend:
    image: bhoominaik16/todo-frontend:latest
    container_name: todo_frontend
    ports:
      - "3001:80"
    depends_on:
      - backend

  mongo:
    image: mongo:6
    container_name: todo_mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: